# Generated by Django 3.2.9 on 2023-08-16 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactblog', '0008_userreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='answer',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='question1',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
