# Generated by Django 3.2.9 on 2023-08-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactblog', '0009_auto_20230816_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='answer',
            new_name='answer1',
        ),
        migrations.AddField(
            model_name='blog',
            name='answer2',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='question2',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
